/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.oscarmaestre.jchip8.gui;

import javax.swing.JLabel;

/**
 *
 * @author usuario
 */
public class DebugPanel extends javax.swing.JPanel {

    JLabel labels[];
    /**
     * Creates new form DebugPanel
     */
    public DebugPanel() {
        initComponents();
        
        this.labels=new JLabel[]{
            this.lblValueV0, this.lblValueV1,
            this.lblValueV2, this.lblValueV3,
            this.lblValueV4, this.lblValueV5,
            this.lblValueV6, this.lblValueV7,
            this.lblValueV8, this.lblValueV9,
            this.lblValueV10, this.lblValueV11,
            this.lblValueV12, this.lblValueV13,
            this.lblValueV14, this.lblValueV15,
        };
    }
    public void setPC(int nuevoPC){
        this.lblValuePC.setText(""+nuevoPC);
    }

    public void setRegistersLabels(byte[] registers){
        for (int i=0; i<this.labels.length; i++){
            JLabel label = this.labels[i];
            int value=registers[i] & 0xff;
            label.setText(""+value);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPC = new javax.swing.JLabel();
        lblValuePC = new javax.swing.JLabel();
        lblV0 = new javax.swing.JLabel();
        lblValueV0 = new javax.swing.JLabel();
        lblV1 = new javax.swing.JLabel();
        lblValueV1 = new javax.swing.JLabel();
        lblV2 = new javax.swing.JLabel();
        lblValueV2 = new javax.swing.JLabel();
        lblV3 = new javax.swing.JLabel();
        lblValueV3 = new javax.swing.JLabel();
        lblV4 = new javax.swing.JLabel();
        lblValueV4 = new javax.swing.JLabel();
        lblV5 = new javax.swing.JLabel();
        lblValueV5 = new javax.swing.JLabel();
        lblV6 = new javax.swing.JLabel();
        lblValueV6 = new javax.swing.JLabel();
        lblV7 = new javax.swing.JLabel();
        lblValueV7 = new javax.swing.JLabel();
        lblV8 = new javax.swing.JLabel();
        lblValueV8 = new javax.swing.JLabel();
        lblV9 = new javax.swing.JLabel();
        lblValueV9 = new javax.swing.JLabel();
        lblV10 = new javax.swing.JLabel();
        lblValueV11 = new javax.swing.JLabel();
        lblV11 = new javax.swing.JLabel();
        lblV12 = new javax.swing.JLabel();
        lblV13 = new javax.swing.JLabel();
        lblV14 = new javax.swing.JLabel();
        lblValueV12 = new javax.swing.JLabel();
        lblV15 = new javax.swing.JLabel();
        lblValueV13 = new javax.swing.JLabel();
        lblValueV14 = new javax.swing.JLabel();
        lblValueV15 = new javax.swing.JLabel();
        lblValueV10 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblPC.setText("PC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblPC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValuePC, gridBagConstraints);

        lblV0.setText("V0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV0, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV0, gridBagConstraints);

        lblV1.setText("V1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV1, gridBagConstraints);

        lblV2.setText("V2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV2, gridBagConstraints);

        lblV3.setText("V3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV3, gridBagConstraints);

        lblV4.setText("V4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV4, gridBagConstraints);

        lblV5.setText("V5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV5, gridBagConstraints);

        lblV6.setText("V6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV6, gridBagConstraints);

        lblV7.setText("V7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV7, gridBagConstraints);

        lblV8.setText("V8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV8, gridBagConstraints);

        lblV9.setText("V9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV9, gridBagConstraints);

        lblV10.setText("V10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV11, gridBagConstraints);

        lblV11.setText("V11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV11, gridBagConstraints);

        lblV12.setText("V12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV12, gridBagConstraints);

        lblV13.setText("V13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV13, gridBagConstraints);

        lblV14.setText("V14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV12, gridBagConstraints);

        lblV15.setText("V15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblV15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblValueV10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblV0;
    private javax.swing.JLabel lblV1;
    private javax.swing.JLabel lblV10;
    private javax.swing.JLabel lblV11;
    private javax.swing.JLabel lblV12;
    private javax.swing.JLabel lblV13;
    private javax.swing.JLabel lblV14;
    private javax.swing.JLabel lblV15;
    private javax.swing.JLabel lblV2;
    private javax.swing.JLabel lblV3;
    private javax.swing.JLabel lblV4;
    private javax.swing.JLabel lblV5;
    private javax.swing.JLabel lblV6;
    private javax.swing.JLabel lblV7;
    private javax.swing.JLabel lblV8;
    private javax.swing.JLabel lblV9;
    private javax.swing.JLabel lblValuePC;
    private javax.swing.JLabel lblValueV0;
    private javax.swing.JLabel lblValueV1;
    private javax.swing.JLabel lblValueV10;
    private javax.swing.JLabel lblValueV11;
    private javax.swing.JLabel lblValueV12;
    private javax.swing.JLabel lblValueV13;
    private javax.swing.JLabel lblValueV14;
    private javax.swing.JLabel lblValueV15;
    private javax.swing.JLabel lblValueV2;
    private javax.swing.JLabel lblValueV3;
    private javax.swing.JLabel lblValueV4;
    private javax.swing.JLabel lblValueV5;
    private javax.swing.JLabel lblValueV6;
    private javax.swing.JLabel lblValueV7;
    private javax.swing.JLabel lblValueV8;
    private javax.swing.JLabel lblValueV9;
    // End of variables declaration//GEN-END:variables
}
